### ISSUE TITLE
README does not contain explicit enough instructions to run app locally

### ISSUE THREAD

**Issue by kwhinnery** [TwilioDevEd/call-tracking-laravel#1]
The README should be followable by just about anyone, regardless of technical skill level. There are several items that are not covered:

* How to set up and connect to Postgres - if you decide to use Postgres for dev instead of sqlite, you need to document this dependency and how to set it up, at least on the Mac. Postgres.app is a good choice. Mention what the connection string will be in .env
* How to set environment variables. You mention editing .env "to your needs" but don't mention what is in it, or how to use the file they just edited.
* Most platforms require a database driver to be installed - on the Mac, you need to do `brew install php56-pdo-pgsql` (or similar) or running the migrations will fail
* you mention that you can configure an app SID in `.env` but don't say how to do it or what the environment variable should be called.

**Comment by jsantos17** [comment]
@kwhinnery ohh you're right I forgot to update the `.env.example` to include TWILIO_APP_SID. I will add instructions on using Postgres.app and the brew command too. Thanks!
