### ISSUE TITLE
MySQL or MariaDB?

### ISSUE THREAD

**Issue by itsazzad** [TwilioDevEd/call-tracking-laravel#12]
Can I use with MySQL or MariaDB?

**Comment by mcelicalderon** [comment]
Sure @itsazzad , by default this app uses Postgres, but changing it to use MySQL should be Simple. (I have never tried using MariaDB with a Laravel app)

Take a look at [this file](https://github.com/TwilioDevEd/call-tracking-laravel/blob/master/config/database.php)

Try adding this

```
'mysql' => [
            'driver'    => 'mysql',
            'host'     => $host,
            'database' => $database,
            'username' => $username,
            'password' => $password,
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
        ],
```

and changing [line 36](https://github.com/TwilioDevEd/call-tracking-laravel/blob/master/config/database.php#L36) to `mysql`
