### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by itsazzad** [TwilioDevEd/call-tracking-laravel#13]
Its something surprising. First the dashboard comes. After clicking on the App Configuration it moved to a https://www.twilio.com/user/account/apps/AP{32bit hash} page.
And dashboard started with the error below:

```
FatalErrorException in LeadController.php line 115:
Call to undefined method Twilio\Rest\Api\V2010\Account\ApplicationInstance::sid()
```

**Comment by itsazzad** [comment]
Seems to be because no Sid is being created?

**Comment by mcelicalderon** [comment]
#14 Fixed this
