### ISSUE TITLE
UI too messy/confusing in current state

### ISSUE THREAD

**Issue by kwhinnery** [TwilioDevEd/call-tracking-laravel#5]
We're not super concerned with visual polish on these, but in it's current state the UI is not presentable. Normally I wouldn't mind if the paths are different or the UX diverging slightly, but the deviations from the Django app's UX were not in a positive direction. 

To eliminate any confusion about what is desired, let's precisely follow UX for the [Django implementation](https://github.com/TwilioDevEd/call-tracking-django):

1. The "dashboard" should have the list of editable lead sources in a left column, and charts for lead distribution on the right. There should be a form to search for a new number to add as a lead source on the dashboard as well
2. Searching for a number should initiate a workflow where you select from available numbers to purchase
3. After selecting a number, it should be purchased with the Twilio API, and then associated with a lead source, that you edit with a name and forwarding number.

I would check out and run the Django app locally, and very closely mirror it's layout and UX.

**Comment by jsantos17** [comment]
@kwhinnery 

Does it look okay now?

![](http://i.imgur.com/9aWxMS3.gif)

**Comment by kwhinnery** [comment]
@jsantos17 looks much better now, but the grid on the home page is still off - you should be able to use Bootstrap's grid system to prevent the content from overflowing the header. Once that's addressed it looks good.

**Comment by jsantos17** [comment]
Yeah, I had some misplaced tags in the master template. Should be fixed now.
